kind: pipeline
name: ls-pro

steps:
  - name: build
    image: golang:1.13-alpine
    commands:
      - mkdir build
      - env GOARCH=arm go build -o build/ls-pro-arm .
      - env GOARCH=arm64 go build -o build/ls-pro-arm64 .
      - env GOARCH=amd64 go build -o build/ls-pro-amd64 .

  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: {{ ACCESS_TOKEN }}
      files: build/*
      title: Release ${DRONE_TAG}
    when:
      event: tag